### ISSUE TITLE
Core dump during processing in pathological situation

### ISSUE THREAD

**Issue by matthaeusheer** [cybathlon-at-school/planvec#35]
```
Traceback (most recent call last):
  File "planvec/gui/processing.py", line 81, in run
  File "planvec/gui/processing.py", line 71, in process_frame
  File "planvec/pipeline.py", line 64, in run_pipeline
  File "planvec/utils/timing.py", line 14, in timed
  File "planvec/img_proc.py", line 106, in find_contours
  File "skimage/_shared/utils.py", line 156, in fixed_func
  File "skimage/measure/_find_contours.py", line 151, in find_contours
  File "skimage/measure/_find_contours.py", line 188, in _assemble_contours
KeyError: (0.0, 108)
[1]    12521 abort (core dumped)  ./main
```

**Comment by matthaeusheer** [comment]
Fixed with try except workaround - seems to be a bug in skimage library.
